//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentaAutos.StoreProcedure
{
    using System;
    
    public partial class ListarAutomovilesDisponibles_SP1_Result1
    {
        public long ID_AUTOMOVIL { get; set; }
        public string GAMA { get; set; }
        public long PRECIO { get; set; }
        public string NOMBRE_MARCA { get; set; }
        public string NOMBRE_TIPO { get; set; }
    }
}
