//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentaAutos.StoreProcedure
{
    using System;
    using System.Collections.Generic;
    
    public partial class RENTA
    {
        public long ID_RENTA { get; set; }
        public long PRECIO { get; set; }
        public System.DateTime FECHA_ALQUILER { get; set; }
        public long ID_AUTOMOVIL { get; set; }
        public long ID_USUARIO { get; set; }
    
        public virtual AUTOMOVIL AUTOMOVIL { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
