//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentaAutos.StoreProcedure
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SP_DB_RENTA_AUTO_Entities : DbContext
    {
        public SP_DB_RENTA_AUTO_Entities()
            : base("name=SP_DB_RENTA_AUTO_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUTOMOVIL> AUTOMOVIL { get; set; }
        public virtual DbSet<MARCA> MARCA { get; set; }
        public virtual DbSet<RENTA> RENTA { get; set; }
        public virtual DbSet<ROL> ROL { get; set; }
        public virtual DbSet<TIPO> TIPO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    
        public virtual ObjectResult<ListarAutomovilesActivos_SP_Result> ListarAutomovilesActivos_SP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarAutomovilesActivos_SP_Result>("ListarAutomovilesActivos_SP");
        }
    
        public virtual ObjectResult<ListarAutomovilesDisponibles_SP_Result> ListarAutomovilesDisponibles_SP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarAutomovilesDisponibles_SP_Result>("ListarAutomovilesDisponibles_SP");
        }
    
        public virtual ObjectResult<ListarMarcasActivas_SP_Result> ListarMarcasActivas_SP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarMarcasActivas_SP_Result>("ListarMarcasActivas_SP");
        }
    
        public virtual ObjectResult<ListarRolesActivos_SP_Result> ListarRolesActivos_SP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarRolesActivos_SP_Result>("ListarRolesActivos_SP");
        }
    
        public virtual ObjectResult<ListarTiposActivos_SP_Result> ListarTiposActivos_SP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarTiposActivos_SP_Result>("ListarTiposActivos_SP");
        }
    
        public virtual ObjectResult<ListarUsuarios_SP_Result> ListarUsuarios_SP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarUsuarios_SP_Result>("ListarUsuarios_SP");
        }
    
        public virtual int SoftDeleteAutomovilById_SP(Nullable<long> iD_AUTOMOVIL)
        {
            var iD_AUTOMOVILParameter = iD_AUTOMOVIL.HasValue ?
                new ObjectParameter("ID_AUTOMOVIL", iD_AUTOMOVIL) :
                new ObjectParameter("ID_AUTOMOVIL", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SoftDeleteAutomovilById_SP", iD_AUTOMOVILParameter);
        }
    
        public virtual int SoftDeleteMarcaById_SP(Nullable<long> iD_MARCA)
        {
            var iD_MARCAParameter = iD_MARCA.HasValue ?
                new ObjectParameter("ID_MARCA", iD_MARCA) :
                new ObjectParameter("ID_MARCA", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SoftDeleteMarcaById_SP", iD_MARCAParameter);
        }
    
        public virtual int SoftDeleteTipoById_SP(Nullable<long> iD_TIPO)
        {
            var iD_TIPOParameter = iD_TIPO.HasValue ?
                new ObjectParameter("ID_TIPO", iD_TIPO) :
                new ObjectParameter("ID_TIPO", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SoftDeleteTipoById_SP", iD_TIPOParameter);
        }
    
        public virtual ObjectResult<ListarAutomovilesDisponibles_SP1_Result1> ListarAutomovilesDisponibles_SP1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarAutomovilesDisponibles_SP1_Result1>("ListarAutomovilesDisponibles_SP1");
        }
    }
}
